/**
 * @module Home
 * @description Main page component — the single-page QA test case generation interface.
 *
 * Layout Architecture (12-column grid):
 * - Left (3 cols): Jira ticket input form with 9 configurable fields
 * - Center (6 cols): Generated test case results with animated cards
 * - Right (3 cols): System architecture reference panel
 *
 * Data Flow:
 * 1. User fills out the Jira ticket form (pre-populated with sample APP-1024 data)
 * 2. On submit, the form data is transformed into a JiraTicket payload
 *    (acceptance_criteria split by newlines, labels split by commas)
 * 3. The useGenerateTestCases mutation (generated by Orval from OpenAPI spec)
 *    sends POST /api/generate with the payload
 * 4. On success, test case cards render with staggered animations
 * 5. Raw JSON toggle provides full response inspection
 *
 * State Management:
 * - Form state: React useState with controlled inputs
 * - Server state: React Query mutation (useGenerateTestCases)
 * - UI state: showJson toggle for raw output panel
 *
 * The mutation hook expects { data: payload } wrapping per Orval's
 * generated interface convention.
 *
 * @author Asif
 */

import { useState } from "react";
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import { vscDarkPlus } from "react-syntax-highlighter/dist/esm/styles/prism";
import { motion, AnimatePresence } from "framer-motion";
import { Layers, Bug, Sparkles, AlertCircle, FileJson, ChevronDown } from "lucide-react";
import {
  Card, CardContent, CardHeader, CardTitle,
  Button, Input, Textarea, Select, Label,
} from "@/components/ui/primitives";
import { ArchitecturePanel } from "@/components/ArchitecturePanel";
import { TestCaseCard } from "@/components/TestCaseCard";
import { useGenerateTestCases } from "@workspace/api-client-react";
import type { GenerateTestCasesResponse, JiraTicket } from "@workspace/api-client-react";

export function Home() {
  /** Toggle for raw JSON output panel visibility */
  const [showJson, setShowJson] = useState(false);

  /**
   * Form state for all 9 Jira ticket fields.
   * Pre-populated with a realistic sample ticket (APP-1024) for immediate demo use.
   */
  const [formData, setFormData] = useState<{
    ticket_id: string;
    summary: string;
    description: string;
    acceptance_criteria: string;
    issue_type: string;
    priority: string;
    component: string;
    labels: string;
    environment: string;
  }>({
    ticket_id: "APP-1024",
    summary: "User can update profile picture",
    description:
      "Add support for changing profile image from account settings. User can upload JPG or PNG images up to 5 MB.",
    acceptance_criteria:
      "User can upload JPG or PNG image\nMaximum allowed size is 5 MB\nInvalid file type should show validation error\nUploaded image should be displayed after successful save",
    issue_type: "story",
    priority: "high",
    component: "profile",
    labels: "ui, upload, settings",
    environment: "staging",
  });

  /** React Query mutation hook — generated from OpenAPI spec via Orval */
  const mutation = useGenerateTestCases();

  /** Generic change handler for all controlled form inputs */
  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>,
  ) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  /**
   * Form submission handler.
   * Transforms flat form state into the JiraTicket API payload:
   * - acceptance_criteria: newline-separated string → string[]
   * - labels: comma-separated string → string[]
   * - Empty optional fields are set to undefined (omitted from JSON)
   */
  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setShowJson(false);

    const payload: JiraTicket = {
      ticket_id: formData.ticket_id,
      summary: formData.summary,
      description: formData.description || undefined,
      acceptance_criteria: formData.acceptance_criteria
        .split("\n")
        .map((s) => s.trim())
        .filter(Boolean),
      issue_type: formData.issue_type || undefined,
      priority: formData.priority || undefined,
      component: formData.component || undefined,
      labels: formData.labels
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean),
      environment: formData.environment || undefined,
    };

    mutation.mutate({ data: payload });
  };

  /** Derived state from the mutation for cleaner JSX */
  const result = mutation.data;
  const isGenerating = mutation.isPending;
  const errorMessage = mutation.isError
    ? mutation.error instanceof Error
      ? mutation.error.message
      : "An unexpected error occurred during generation."
    : null;

  return (
    <div className="min-h-screen bg-[#0B0C10] text-gray-200 selection:bg-indigo-500/30">
      {/* Sticky header with app branding and system label */}
      <header className="sticky top-0 z-50 border-b border-white/10 bg-[#0B0C10]/80 backdrop-blur-xl">
        <div className="max-w-screen-2xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-indigo-500 to-cyan-400 p-0.5 shadow-lg shadow-indigo-500/20">
              <div className="w-full h-full bg-[#0B0C10] rounded-[6px] flex items-center justify-center">
                <Bug className="w-4 h-4 text-cyan-400" />
              </div>
            </div>
            <h1 className="font-sans font-bold text-xl tracking-tight text-white">
              Asif AI Jira QA{" "}
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 to-cyan-400">
                Copilot
              </span>
            </h1>
          </div>
          <div className="text-sm font-medium text-gray-400 flex items-center gap-2">
            <Layers className="w-4 h-4" />
            Test Generation System
          </div>
        </div>
      </header>

      <main className="max-w-screen-2xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">

          {/* LEFT COLUMN: Jira Ticket Input Form (3/12 cols) */}
          <div className="lg:col-span-3 space-y-6">
            <Card className="bg-[#11131A] border-white/5 shadow-xl">
              <CardHeader className="border-b border-white/5 pb-4 bg-white/[0.02]">
                <CardTitle className="text-lg">Ticket Context</CardTitle>
              </CardHeader>
              <CardContent className="pt-6">
                <form onSubmit={handleSubmit} className="space-y-4">
                  <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <Label htmlFor="ticket_id">Ticket ID</Label>
                      <Input
                        id="ticket_id"
                        name="ticket_id"
                        value={formData.ticket_id}
                        onChange={handleChange}
                        required
                      />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="issue_type">Issue Type</Label>
                      <div className="relative">
                        <Select
                          id="issue_type"
                          name="issue_type"
                          value={formData.issue_type}
                          onChange={handleChange}
                        >
                          <option value="story">Story</option>
                          <option value="bug">Bug</option>
                          <option value="task">Task</option>
                          <option value="epic">Epic</option>
                        </Select>
                        <ChevronDown className="absolute right-3 top-3 w-4 h-4 text-gray-400 pointer-events-none" />
                      </div>
                    </div>
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="summary">Summary</Label>
                    <Input
                      id="summary"
                      name="summary"
                      value={formData.summary}
                      onChange={handleChange}
                      required
                    />
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="description">Description</Label>
                    <Textarea
                      id="description"
                      name="description"
                      value={formData.description}
                      onChange={handleChange}
                      className="min-h-[100px]"
                    />
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="acceptance_criteria">
                      Acceptance Criteria{" "}
                      <span className="text-gray-500 text-xs font-normal">(One per line)</span>
                    </Label>
                    <Textarea
                      id="acceptance_criteria"
                      name="acceptance_criteria"
                      value={formData.acceptance_criteria}
                      onChange={handleChange}
                      className="min-h-[120px] whitespace-pre"
                    />
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <Label htmlFor="priority">Priority</Label>
                      <div className="relative">
                        <Select
                          id="priority"
                          name="priority"
                          value={formData.priority}
                          onChange={handleChange}
                        >
                          <option value="low">Low</option>
                          <option value="medium">Medium</option>
                          <option value="high">High</option>
                          <option value="critical">Critical</option>
                        </Select>
                        <ChevronDown className="absolute right-3 top-3 w-4 h-4 text-gray-400 pointer-events-none" />
                      </div>
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="component">Component</Label>
                      <Input
                        id="component"
                        name="component"
                        value={formData.component}
                        onChange={handleChange}
                      />
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <Label htmlFor="environment">Environment</Label>
                      <Input
                        id="environment"
                        name="environment"
                        value={formData.environment}
                        onChange={handleChange}
                      />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="labels">
                        Labels{" "}
                        <span className="text-gray-500 text-xs font-normal">(CSV)</span>
                      </Label>
                      <Input
                        id="labels"
                        name="labels"
                        value={formData.labels}
                        onChange={handleChange}
                      />
                    </div>
                  </div>

                  {/* Primary CTA — triggers the AI generation mutation */}
                  <Button
                    type="submit"
                    className="w-full h-12 text-base mt-2 bg-gradient-to-r from-indigo-600 to-indigo-500 hover:from-indigo-500 hover:to-indigo-400 shadow-lg shadow-indigo-500/25 border border-indigo-400/20"
                    isLoading={isGenerating}
                  >
                    {!isGenerating && <Sparkles className="w-5 h-5 mr-2" />}
                    {isGenerating ? "Analyzing & Generating..." : "Generate Test Cases"}
                  </Button>
                </form>
              </CardContent>
            </Card>
          </div>

          {/* CENTER COLUMN: Results Panel (6/12 cols) */}
          <div className="lg:col-span-6 space-y-6">
            {/* Empty state — shown before first generation */}
            {!result && !isGenerating && !errorMessage && (
              <div className="h-[400px] rounded-xl border border-dashed border-white/10 flex flex-col items-center justify-center text-center px-6">
                <div className="w-16 h-16 rounded-2xl bg-white/5 flex items-center justify-center mb-4">
                  <Sparkles className="w-8 h-8 text-indigo-400/50" />
                </div>
                <h3 className="text-xl font-sans text-white mb-2">Ready to Generate</h3>
                <p className="text-gray-400 max-w-sm">
                  Submit the Jira ticket context to automatically architect comprehensive QA test
                  cases using GPT-4o mini.
                </p>
              </div>
            )}

            {/* Loading skeleton — pulse animation while awaiting LLM response */}
            {isGenerating && (
              <div className="space-y-4">
                {[1, 2, 3].map((i) => (
                  <Card key={i} className="bg-[#11131A] border-white/5 animate-pulse">
                    <CardContent className="p-6">
                      <div className="flex gap-2 mb-4">
                        <div className="h-5 w-16 bg-white/10 rounded-full" />
                        <div className="h-5 w-16 bg-white/10 rounded-full" />
                      </div>
                      <div className="h-6 w-3/4 bg-white/10 rounded mb-4" />
                      <div className="h-10 w-full bg-white/5 rounded" />
                    </CardContent>
                  </Card>
                ))}
              </div>
            )}

            {/* Error state — displayed on mutation failure */}
            {errorMessage && (
              <Card className="bg-red-500/10 border-red-500/20">
                <CardContent className="p-6 flex items-start gap-4">
                  <AlertCircle className="w-6 h-6 text-red-400 shrink-0 mt-0.5" />
                  <div>
                    <h3 className="text-lg font-semibold text-red-400">Generation Failed</h3>
                    <p className="text-red-300/80 mt-1">{errorMessage}</p>
                  </div>
                </CardContent>
              </Card>
            )}

            {/* Success state — rendered test case cards with staggered animations */}
            <AnimatePresence>
              {result && !isGenerating && (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  className="space-y-6"
                >
                  {/* Results header with ticket reference and case count badge */}
                  <div className="flex items-center justify-between pb-2 border-b border-white/10">
                    <div>
                      <h2 className="text-2xl font-sans font-semibold text-white">
                        Generated Test Suite
                      </h2>
                      <p className="text-sm text-gray-400 mt-1">
                        Based on {result.ticket_id}: {result.summary}
                      </p>
                    </div>
                    <div className="px-3 py-1 rounded-full bg-indigo-500/10 text-indigo-400 text-sm font-medium border border-indigo-500/20">
                      {result.generated_test_cases.length} Cases
                    </div>
                  </div>

                  {/* Individual test case cards with staggered entry animations */}
                  <div className="space-y-4">
                    {result.generated_test_cases.map((tc, index) => (
                      <TestCaseCard key={tc.test_case_id} data={tc} index={index} />
                    ))}
                  </div>

                  {/* Collapsible raw JSON output for debugging/inspection */}
                  <div className="pt-8">
                    <button
                      onClick={() => setShowJson(!showJson)}
                      className="flex items-center gap-2 text-sm font-medium text-gray-400 hover:text-white transition-colors"
                    >
                      <FileJson className="w-4 h-4" />
                      {showJson ? "Hide Raw JSON Output" : "View Raw JSON Output"}
                      <ChevronDown
                        className={`w-4 h-4 transition-transform duration-300 ${showJson ? "rotate-180" : ""}`}
                      />
                    </button>

                    <AnimatePresence>
                      {showJson && (
                        <motion.div
                          initial={{ height: 0, opacity: 0 }}
                          animate={{ height: "auto", opacity: 1 }}
                          exit={{ height: 0, opacity: 0 }}
                          className="overflow-hidden mt-4"
                        >
                          <div className="rounded-xl overflow-hidden border border-white/10 text-sm shadow-xl">
                            <SyntaxHighlighter
                              language="json"
                              style={vscDarkPlus}
                              customStyle={{ margin: 0, padding: "1.5rem", background: "#0D0E12" }}
                            >
                              {JSON.stringify(result, null, 2)}
                            </SyntaxHighlighter>
                          </div>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>

          {/* RIGHT COLUMN: Architecture Reference Panel (3/12 cols) */}
          <div className="lg:col-span-3">
            <ArchitecturePanel />
          </div>
        </div>
      </main>
    </div>
  );
}
